// src/data/dataAdmin.js

// 💰 Doanh thu theo tháng
export const revenueData = [
  { month: "Jan", value: 120000, category: "Doanh thu theo gói" },
  { month: "Jan", value: 80000, category: "Doanh thu theo % hoa hồng" },
  { month: "Feb", value: 180000, category: "Doanh thu theo gói" },
  { month: "Feb", value: 100000, category: "Doanh thu theo % hoa hồng" },
  { month: "Mar", value: 150000, category: "Doanh thu theo gói" },
  { month: "Mar", value: 90000, category: "Doanh thu theo % hoa hồng" },
  { month: "Apr", value: 220000, category: "Doanh thu theo gói" },
  { month: "Apr", value: 130000, category: "Doanh thu theo % hoa hồng" },
  { month: "May", value: 200000, category: "Doanh thu theo gói" },
  { month: "May", value: 110000, category: "Doanh thu theo % hoa hồng" },
  { month: "Jun", value: 250000, category: "Doanh thu theo gói" },
  { month: "Jun", value: 150000, category: "Doanh thu theo % hoa hồng" },
];

// 👥 Người dùng mới theo thời gian
export const newUserData = [
  { month: "Jan", value: 120, category: "Người bán" },
  { month: "Jan", value: 300, category: "Người mua" },
  { month: "Feb", value: 150, category: "Người bán" },
  { month: "Feb", value: 400, category: "Người mua" },
  { month: "Mar", value: 180, category: "Người bán" },
  { month: "Mar", value: 450, category: "Người mua" },
  { month: "Apr", value: 200, category: "Người bán" },
  { month: "Apr", value: 480, category: "Người mua" },
];

// 🚗 Số lượng xe đăng bán theo trạng thái
export const carStatusData = [
  { status: "Đã duyệt", value: 120 },
  { status: "Chờ duyệt", value: 60 },
  { status: "Bị từ chối", value: 30 },
];

// 🔄 Số lượng giao dịch theo trạng thái
export const transactionStatusData = [
  { status: "Thành công", value: 80 },
  { status: "Đang xử lý", value: 25 },
  { status: "Thất bại", value: 10 },
];
// bài đăng
export const post = [
  {
    id: 1,
    key: 1,
    postId: 101,
    title: "Xe Toyota Camry 2020",
    createdBy: "Nguyễn Văn A",
    createAt: "2025-10-05",
    description: "Xe chạy 30.000 km, bảo dưỡng đầy đủ, nội thất mới 95%.",
    status: "PENDING",
  },
  {
    id:2,
    key: 2,
    postId: 102,
    title: "Mazda CX-5 2019",
    createdBy: "Trần Thị B",
    createAt: "2025-10-07",
    description: "Xe gia đình, không va quẹt, có camera 360.",
    status: "APPROVED",
  },
  {
    id:3,
    key: 3,
    postId: 103,
    title: "Honda City 2021",
    createdBy: "Phạm Văn C",
    createAt: "2025-10-09",
    description: "Xe chính chủ, đã kiểm định định kỳ, sẵn sàng giao.",
    status: "REJECTED",
  },
  {
    id:4,
    key: 4,
    postId: 104,
    title: "Hyundai Tucson 2020",
    createdBy: "Lê Minh D",
    createAt: "2025-10-06",
    description: "Xe mới đi 25.000 km, bản đặc biệt, có cảm biến quanh xe.",
    status: "PENDING",
  },
  {
    id:5,
    key: 5,
    postId: 105,
    title: "Ford Ranger Wildtrak 2021",
    createdBy: "Đỗ Thị E",
    createAt: "2025-10-04",
    description: "Xe bán tải 2 cầu, bảo dưỡng chính hãng, ngoại thất mới.",
    status: "APPROVED",
  },
  {
    id:6,
    key: 6,
    postId: 106,
    title: "VinFast Lux A2.0 2022",
    createdBy: "Nguyễn Văn F",
    createAt: "2025-10-03",
    description: "Xe Việt, bảo hành chính hãng, nội thất sang trọng.",
    status: "REJECTED",
  },
  {
    id:7,
    key: 7,
    postId: 107,
    title: "Kia Seltos 2021",
    createdBy: "Phan Thị G",
    createAt: "2025-10-02",
    description: "Xe màu trắng, bản cao cấp, hỗ trợ vay ngân hàng.",
    status: "PENDING",
  },
  {
    id:8,
    key: 8,
    postId: 108,
    title: "Mitsubishi Xpander 2020",
    createdBy: "Trương Văn H",
    createAt: "2025-10-01",
    description: "Xe gia đình, không taxi, nội thất nguyên bản.",
    status: "APPROVED",
  },
  {
    id:9,
    key: 9,
    postId: 109,
    title: "Mercedes C300 AMG 2019",
    createdBy: "Vũ Thị I",
    createAt: "2025-09-30",
    description: "Xe sang, chạy 40.000 km, bảo dưỡng hãng, nội thất da.",
    status: "PENDING",
  },
  {
    id:10,
    key: 10,
    postId: 110,
    title: "BMW X3 2020",
    createdBy: "Lý Văn K",
    createAt: "2025-09-28",
    description: "Xe nhập Đức, động cơ 2.0 Turbo, vận hành êm.",
    status: "REJECTED",
  },
  {
    id:11,
    key: 11,
    postId: 111,
    title: "Toyota Fortuner 2021",
    createdBy: "Phạm Thị L",
    createAt: "2025-09-27",
    description: "Xe SUV 7 chỗ, máy dầu, gầm cao, phù hợp gia đình.",
    status: "APPROVED",
  },
  {
    id:12,
    key: 12,
    postId: 112,
    title: "Hyundai Elantra 2018",
    createdBy: "Đặng Văn M",
    createAt: "2025-09-26",
    description: "Xe đi 60.000 km, sơn zin 90%, bảo dưỡng đều.",
    status: "PENDING",
  },
  {
    id:13,
    key: 13,
    postId: 113,
    title: "Honda CR-V 2022",
    createdBy: "Trần Thị N",
    createAt: "2025-09-25",
    description: "Xe chạy 10.000 km, bản cao cấp, có camera 360.",
    status: "APPROVED",
  },
  {
    id:14,
    key: 14,
    postId: 114,
    title: "Mazda 3 2020",
    createdBy: "Nguyễn Văn O",
    createAt: "2025-09-24",
    description: "Xe sedan, màu đỏ, nội thất da nâu, tiết kiệm xăng.",
    status: "PENDING",
  },
  {
    id:15,
    key: 15,
    postId: 115,
    title: "VinFast Fadil 2021",
    createdBy: "Phạm Thị P",
    createAt: "2025-09-23",
    description: "Xe nhỏ gọn, tiết kiệm nhiên liệu, phù hợp đô thị.",
    status: "REJECTED",
  },
  {
    id:16,
    key: 16,
    postId: 116,
    title: "Ford Everest 2022",
    createdBy: "Trần Văn Q",
    createAt: "2025-09-22",
    description: "Xe gầm cao, máy dầu, nội thất sang trọng.",
    status: "APPROVED",
  },
  {
    id:17,
    key: 17,
    postId: 117,
    title: "Suzuki XL7 2021",
    createdBy: "Đỗ Thị R",
    createAt: "2025-09-21",
    description: "Xe 7 chỗ, tiết kiệm xăng, bảo dưỡng chính hãng.",
    status: "PENDING",
  },
  {
    id:18,
    key: 18,
    postId: 118,
    title: "Peugeot 3008 2020",
    createdBy: "Nguyễn Văn S",
    createAt: "2025-09-20",
    description: "Xe Pháp, sang trọng, nhiều công nghệ hiện đại.",
    status: "APPROVED",
  },
  {
    id:19,
    key: 19,
    postId: 119,
    title: "Mitsubishi Outlander 2019",
    createdBy: "Phan Văn T",
    createAt: "2025-09-19",
    description: "Xe đi ít, không va chạm, nội thất như mới.",
    status: "REJECTED",
  },
  {
    id:20,
    key: 20,
    postId: 120,
    title: "Toyota Corolla Cross 2021",
    createdBy: "Lê Thị U",
    createAt: "2025-09-18",
    description: "Xe hybrid, tiết kiệm xăng, vận hành mượt mà.",
    status: "PENDING",
  },
];

// kiểm định xe
export const vehicleInspection = [
  {
    key: 1,
    productid: 1,
    productname: "Toyota Camry 2020",
    model: "Camry",
    type: "Sedan",
    status: "Pending",
  },
  {
    key: 2,
    productid: 2,
    productname: "Honda CR-V 2021",
    model: "CR-V",
    type: "SUV",
    status: "Pending",
  },
  {
    key: 3,
    productid: 3,
    productname: "Ford Ranger 2019",
    model: "Ranger",
    type: "Pickup",
    status: "Pending",
  },
];

// kho xe
export const productsData = [
  {
    id:1,
    productid: 1,
    productname: "Toyota Camry 2020",
    model: "Camry 2.5Q",
    type: "Sedan",
    cost: 890000000,
    userid: "Nguyễn Văn A",
    description: "Xe đã qua kiểm định, nội thất 95%, sẵn sàng giao.",
    amount: 1,
    in_warehouse: true,
    createdat: "2025-10-01",
    updatedat: "2025-10-05",
    status: "inspection_passed",
  },
  {
    id:2,
    productid: 2,
    productname: "Mazda CX-5 2019",
    model: "CX-5 Premium",
    type: "SUV",
    cost: 780000000,
    userid: "Trần Thị B",
    description: "Xe SUV gia đình, đã đạt kiểm định.",
    amount: 1,
    in_warehouse: true,
    createdat: "2025-09-20",
    updatedat: "2025-10-02",
    status: "inspection_passed",
  },
  {
    id:3,
    productid: 3,
    productname: "Ford Ranger 2021",
    model: "Ranger Wildtrak",
    type: "Truck",
    cost: 950000000,
    userid: "Phạm Văn C",
    description: "Xe bán tải mạnh mẽ, kiểm định đạt chuẩn.",
    amount: 1,
    in_warehouse: true,
    createdat: "2025-09-15",
    updatedat: "2025-10-05",
    status: "inspection_passed",
  },
];

export const orders = [
  {
    id: 1,
    productName: "VinFast VF 8 Eco 2023",
    buyerName: "Nguyễn Văn A",
    sellerName: "Lê Thị Z",
    deposit: 500000000,
    status: "PENDING",
    note: "",
    totalPrice: 2000000000,
    createdAt: "2025-10-09 09:00:00",
  },
  {
    id: 2,
    productName: "Tesla Model 3 Performance 2024",
    buyerName: "Trần Thị B",
    sellerName: "Phạm Văn Y",
    deposit: 1000000000,
    status: "APPROVED",
    note: "Xe đạt đủ điều kiện, giao dịch đã được duyệt.",
    totalPrice: 3200000000,
    createdAt: "2025-10-08 13:20:00",
  },
  {
    id: 3,
    productName: "Toyota Camry 2.5Q 2022",
    buyerName: "Lê Hoàng C",
    sellerName: "Nguyễn Thị X",
    deposit: 300000000,
    status: "REJECTED",
    note: "Xe có vấn đề kỹ thuật, không đủ điều kiện giao dịch.",
    totalPrice: 1500000000,
    createdAt: "2025-10-09 14:00:00",
  },
  {
    id: 4,
    productName: "Kia EV6 GT-Line 2023",
    buyerName: "Phạm Minh D",
    sellerName: "Trần Thị Y",
    deposit: 800000000,
    status: "DEPOSITED",
    note: "Buyer đã đặt cọc, chờ duyệt.",
    totalPrice: 1800000000,
    createdAt: "2025-10-10 08:30:00",
  },
  {
    id: 5,
    productName: "Hyundai Ioniq 5 Ultimate 2023",
    buyerName: "Đặng Thu E",
    sellerName: "Nguyễn Văn Z",
    deposit: 600000000,
    status: "PENDING",
    note: "",
    totalPrice: 1650000000,
    createdAt: "2025-10-10 09:10:00",
  },
];

export const disputeData = [
  {
    id: 1,
    buyer: "Nguyễn Văn A",
    seller: "Trần Văn B",
    reason: "Sản phẩm bị lỗi",
    status: "Pending",
  },
  {
    id: 2,
    buyer: "Lê Thị C",
    seller: "Phạm Văn D",
    reason: "Giao hàng chậm",
    status: "Resolved",
  },
];

// Dữ liệu giả cho bảng package services
export const packageData = [
  {
    packageid: 1,
    name: "Gói Cơ Bản",
    duration_months: 1,
    max_batteries: 5,
    max_cars: 2,
    price: 99000,
    created_at: "2025-09-01",
  },
  {
    packageid: 2,
    name: "Gói Nâng Cao",
    duration_months: 3,
    max_batteries: 15,
    max_cars: 6,
    price: 249000,
    created_at: "2025-09-01",
  },
  {
    packageid: 3,
    name: "Gói Cao Cấp",
    duration_months: 6,
    max_batteries: 50,
    max_cars: 20,
    price: 499000,
    created_at: "2025-09-01",
  },
];

// Dữ liệu giả cho bảng user packages
export const userPackageData = [
  {
    userpackageid: 1,
    username: "nguyenvana",
    packageid: 1,
    name: "Gói Cơ Bản",
    purchase_date: "2025-10-01",
    expiry_date: "2025-11-01",
    remaining_batteries: 3,
    remaining_cars: 1,
  },
  {
    userpackageid: 2,
    username: "tranthib",
    packageid: 2,
    name: "Gói Nâng Cao",
    purchase_date: "2025-09-15",
    expiry_date: "2025-12-15",
    remaining_batteries: 10,
    remaining_cars: 4,
  },
  {
    userpackageid: 3,
    username: "phamvanc",
    packageid: 3,
    name: "Gói Cao Cấp",
    purchase_date: "2025-07-01",
    expiry_date: "2025-12-31",
    remaining_batteries: 45,
    remaining_cars: 17,
  },
];

export const userData = [
  {
    userid: 1,
    displayname: "Nguyễn Văn A",
    username: "nguyenvana",
    email: "a@gmail.com",
    phone: "0123456789",
    isactive: true,
    created_at: "2025-10-01",
    updated_at: "2025-10-10",
    dateofbirth: "2000-05-15",
    role: "pending_buyer",
    avatar: "",
  },
  {
    userid: 2,
    displayname: "Trần Thị B",
    username: "tranthib",
    email: "b@gmail.com",
    phone: "0987654321",
    isactive: false,
    created_at: "2025-09-20",
    updated_at: "2025-10-05",
    dateofbirth: "1999-09-12",
    role: "buyer",
    avatar: "",
  },
  {
    userid: 3,
    displayname: "Phạm Văn C",
    username: "phamvanc",
    email: "c@gmail.com",
    phone: "0777777777",
    isactive: true,
    created_at: "2025-08-15",
    updated_at: "2025-10-11",
    dateofbirth: "1998-02-22",
    role: "user",
    avatar: "",
  },
];